# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
